site_name: Phát triển ứng dụng Web mã nguồn mở

theme:
  name: material
  language: vi

nav:
  - Trang chủ: index.md

  - Chuẩn bị:
      - Pre-Lab 00 - Chuẩn bị môi trường: preparation/Pre-Lab-00_Environment-Setup-Windows.md

  - Thực hành:
      - Hands-on 01 - PHP và Docker: hands-on/Hands-on-01_PHP-Docker_Baseline.md
      - Hands-on 02 - MySQL-Database-Schema-Seed: hands-on/Hands-on-02_MySQL-Database-Schema-Seed.md
      - Hands-on 03 - PHP-MySQLi-Category-Listing: hands-on/Hands-on-03_PHP-MySQLi-Category-Listing.md
      - Hands-on 04 - Xây dựng CRUD quản lý danh mục: hands-on/Hands-on-04_Category-CRUD.md
      - Hands-on 05 - Xây dựng CRUD quản lý sản phẩm: hands-on/Hands-on-05_Product-Relational-Data.md
      - Hands-on 06 – Upload hình ảnh sản phẩm với PHP: hands-on/Hands-on-06_Upload-Product-Images.md
      - Hands-on 07 – Quản lý hình ảnh sản phẩm khi cập nhật: hands-on/Hands-on-07_Manage-Product-Images.md
      - Hands-on 08 – Tổ chức khu vực quản trị và giao diện người dùng: hands-on/Hands-on-08_Admin-Frontend-Structure.md
      - Hands-on 09 – Xây dựng trang danh sách và chi tiết sản phẩm: hands-on/Hands-on-09_Product-Storefront-and-Detail.md
      - Hands-on 10 – Tìm kiếm, lọc và phân trang sản phẩm: hands-on/Hands-on-10_Product-Search-Filter-and-Pagination.md
      - Hands-on 11 – Xây dựng giỏ hàng với PHP Session: hands-on/Hands-on-11_Shopping-Cart-with-PHP-Session.md
      - Hands-on 12 – Xử lý đặt hàng và lưu đơn hàng vào MySQL: hands-on/Hands-on-12_Checkout-and-Order-Processing.md
      - Hands-on 13 – Quản lý đơn hàng trong khu vực Admin: hands-on/Hands-on-13_Admin-Order-Management.md
      - Hands-on 14 – Đăng ký, đăng nhập và tài khoản khách hàng: hands-on/Hands-on-14_Customer-Authentication-and-Accounts.md
      - Hands-on 15 – REST API và Fetch API: hands-on/Hands-on-15_REST-API-and-Fetch.md
  - Hướng dẫn:
      - Git và GitHub: guides/Mini-Hands-on_Git-Push-GitHub.md